# Generated by Django 4.2 on 2024-12-23 21:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='is_sold',
        ),
        migrations.RemoveField(
            model_name='item',
            name='price',
        ),
    ]
